### ISSUE TITLE
Volume control

### ISSUE THREAD

**Issue by overlordt** [Romkabouter/Matrix-Voice-ESP32-MQTT-Audio-Streamer#17]
Is it possible to define a fixed volume level in code or otherwise configurable over for example MQTT?

I would like to use a speaker connected to the jack output that has no volume control capabilities, but this would also be useful for speakers connected to the speaker output on the matrix Voice.

**Comment by Romkabouter** [comment]
Yes ,it is possible. We can write a volume % to the kConfBaseAddress + 8 address which should control the volume.
I will have a go at it, nice feature :)

**Comment by Romkabouter** [comment]
Done in release 5.1
