### ISSUE TITLE
Can't build "OTABuilder" with current Makefile

### ISSUE THREAD

**Issue by systemofapwne** [Romkabouter/Matrix-Voice-ESP32-MQTT-Audio-Streamer#18]
Issuing "make" within the "OTABuilder" folder fails with

``Makefile:6:` /make/project.mk: No such file or directory
make: *** No rule to make target '/make/project.mk'.  Stop.
``
It seems like, the makefile is not configured at all. Please add make-instructions to the Makefile so one can simply compile it via "make"

**Comment by Romkabouter** [comment]
Have you installed the esp-idf?
