### ISSUE TITLE
Use Program on Non-ESP32 Version

### ISSUE THREAD

**Issue by nolimits2k** [Romkabouter/Matrix-Voice-ESP32-MQTT-Audio-Streamer#20]
Hi @Romkabouter,

I am just getting started with this and was wondering if it´s possible to also use your program on the Non-ESP32 version of matrix voice?

Best regards,
Thomas

**Comment by Romkabouter** [comment]
Hi there, you cannot flash anything onto the non-esp32 version. So no, this software (or any other software for the esp32) can be used.
