### ISSUE TITLE
won't connect to mosquitto, socket error

### ISSUE THREAD

**Issue by wzbfyb** [Romkabouter/Matrix-Voice-ESP32-MQTT-Audio-Streamer#27]
Hi,

when Matrix Voice boots up, the leds change blue/red all the time and in mosquito log I see:
`
1608233147: New connection from 192.168.132.27 on port 1883.
1608233147: Socket error on client <unknown>, disconnecting.
`

any hints whats going on there?

**Comment by wzbfyb** [comment]
noticed something: when I setup mosquito to allow anonymous logins, and remove user/pw it works.
seems to be an issue with my password:


username=default
password="W6o4wUc(/76"

I had to use " " for the password, otherwise the ( in the pw would cause a compilation error.

**Comment by Romkabouter** [comment]
Might be a password problem, please do not use a slash as special character

**Comment by wzbfyb** [comment]
most likely, thanks.
Will setup a dedicated user for matrix voice and avoid nasty chars in the password 👍
