### ISSUE TITLE
Question on the code

### ISSUE THREAD

**Issue by Lumy88** [Romkabouter/Matrix-Voice-ESP32-MQTT-Audio-Streamer#3]
Hello Rom,
Thanks for sharing such an amazing work. I'm new in programming, and have a silly question on your code. ( line 331-334&337 of MatrixVoiceAudioServer.ino)

```
for (int i=0;i<message_count;i++) {
        for (uint32_t s = CHUNK*i; s < CHUNK * (i+1); s++) {
            voicebuffer[s-(CHUNK*i)] = mics.Beam(s);
        }      
```

As far as I understanding, voicebuffer only has 256 elements, and the first voicebuffer ( when i =0 ) will be overlapped after running this part of code.

` memcpy(voicemapped,voicebuffer,CHUNK*WIDTH)`

Thus how to copy the voicebuffer to voicemapped from 0-511?

Thank you!

**Comment by Romkabouter** [comment]
voicebuffer has 256 16bit elements, so 512 bytes.
voicemapped is uint_16, while voicebuffer is uint_8

For correct audio, you need to keep the bytes in synch. So 16bit aligned.
Each 16bit sample needs to be copied to 2bytes, that is exactly what the memcpy does.

**Comment by Lumy88** [comment]
Dear Rom,
Thank you very much. Finally, I totally understand your code.
Then I can go on to the next step!

Great Work!
