### ISSUE TITLE
How to set the hotword?

### ISSUE THREAD

**Issue by tahesse** [Romkabouter/Matrix-Voice-ESP32-MQTT-Audio-Streamer#4]
As the title of issue already indicates: I am not quite sure how to set / test the hotword.
Any tips in that regards?

Thanks a lot!

**Comment by Romkabouter** [comment]
You should check the Snips documentation for that: https://docs.snips.ai/

This software only implements the Snips Audio Server, providing an audiostream to Snips

**Comment by tahesse** [comment]
Oh alright, thanks @Romkabouter !
I thought there was a standalone test mode using one of your other repos `matrix_hotword`. Mistake on my side. Thank you for that awesome work you came up with! *thumbs up*
